// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/14/2026, 10:01:32 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/plugins/**/*.{js,ts,mjs}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/composables/**/*.{js,ts,mjs}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/utils/**/*.{js,ts,mjs}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/app.config.{js,ts,mjs}","/Users/abdullahkayed/WorkTabsen/vibecodinng-reviews/tabsense-reviews/frontend/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;